---
- name: 'Install Syncthing'
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - syncthing
    - syncthing-gtk
  become: true

- name: 'Create a syncthing config directory'
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/.config/syncthing"
    state: directory
  become: false

- name: 'Copy syncthing config files'
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ item.link }}"
  with_items:
    - { file: "files/syncthing/config.xml", link: "{{ ansible_env.HOME }}/.config/syncthing/config.xml" }
    - { file: "files/syncthing/cert.pem", link: "{{ ansible_env.HOME }}/.config/syncthing/cert.pem" }
    - { file: "files/syncthing/key.pem", link: "{{ ansible_env.HOME }}/.config/syncthing/key.pem" }
  become: false

- name: 'Enable Syncthing service'
  ansible.builtin.systemd:
    name: "syncthing@{{ ansible_env.USER }}.service"
    enabled: no
    masked: no
    state: stopped
  become: true