---
- name: 'Include vars'
  include_vars:
    file: ubuntu-2004.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "20.04")

- name: 'Include vars'
  include_vars:
    file: ubuntu-2110.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "21.10") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "21.10")

- name: 'Customize Gnome'
  import_role:
    name: petermosmans.customize-gnome

- include_tasks: ubuntu-2004.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "20.04")

- include_tasks: ubuntu-2110.yml
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "21.10") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "21.10")

- name: 'Reboot to apply Gnome settings'
  reboot:
  become: true
