---
- name: 'Write GNOME personal settings with DConf'
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "/org/gnome/desktop/input-sources/current", value: "'uint32 0'" }
    - { key: "/org/gnome/desktop/input-sources/mru-sources", value: "[('xkb', 'us+alt-intl'), ('xkb', 'br')]" }
    - { key: "/org/gnome/desktop/input-sources/sources", value: "[('xkb', 'us+alt-intl'), ('xkb', 'br')]" }
    - { key: "/org/gnome/desktop/input-sources/per-window", value: "false" }
    - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "'@as []'" }
    - { key: "/org/gnome/desktop/peripherals/mouse/speed", value: "'1'" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/speed", value: "'0.38297872340425543'" }
    - { key: "/org/gnome/desktop/peripherals/mouse/two-finger-scrolling-enabled", value: "true" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "true" }
    - { key: "/org/gnome/desktop/interface/cursor-size", value: "24" }
  become: false
