---
- name: 'Docker: Insert GPG Key'
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: 'Docker: Add repository'
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "20.04")
  become: true
  
- name: 'Docker: Add repository'
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04") or
        (ansible_distribution == "Pop!_OS" and ansible_distribution_version == "22.04")
  become: true 

- name: 'Docker: Install package'
  ansible.builtin.apt:
    name: docker-ce
    state: latest
  become: true

- name: 'Docker: Enable service'
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    masked: no
  become: true

- name: 'Docker: Set group docker to user'
  ansible.builtin.command: "usermod -aG docker {{ ansible_env.USER }}"
  become: true

- name: 'Docker Compose: Download the binary'
  ansible.builtin.command: "curl -L 'https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose"
  become: true

- name: 'Docker Compose: Set permission to execute'
  ansible.builtin.command: "chmod +x /usr/local/bin/docker-compose"
  become: true
