---
- name: 'Check if zinit installed'
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.zinit"
  register: zinit_installed
  become: false

- name: 'Download zinit installer'
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/zdharma-continuum/zinit/main/scripts/install.sh
    dest: $HOME/zinit-installer.sh
    mode: 0755
  become: false
  when: zinit_installed.stat.isdir is not defined or not zinit_installed.stat.isdir

- name: 'Execute the zinit installer'
  shell: $HOME/zinit-installer.sh
  become: false
  when: zinit_installed.stat.isdir is not defined or not zinit_installed.stat.isdir

- name: 'Remove the zinit installer'
  file:
    path: $HOME/zinit-installer.sh
    state: absent
  become: false
  when: zinit_installed.stat.isdir is not defined or not zinit_installed.stat.isdir